### ISSUE TITLE
Fix tests and comply to pep8 via flake8 linter

### ISSUE THREAD

**Issue by CozyDoomer** [beatorizu/Jikan-Gateways-API#11]
When I tried to run the unitttests one test failed and I saw some formatting errors that would be detected by most linters.

Can I create a pull request to fix the test and formatting errors?

**Comment by beatorizu** [comment]
Sure! I will assign this issue to you :)

**Comment by CozyDoomer** [comment]
is it okay for you to add the hacktoberfest label?

I will also add tests for the other objects (anime, manga, person) so it''s not just a few lines changed

Thanks

**Comment by beatorizu** [comment]
Label and tests ok
Great work!
