### ISSUE TITLE
We need to search for the animes of a specific season of the year

### ISSUE THREAD

**Issue by beatorizu** [beatorizu/Jikan-Gateways-API#6]
We need to search for the animes of a specific season of the year, you can read more here [https://jikan.docs.apiary.io/#reference/0/season/season-request-example+schema](https://jikan.docs.apiary.io/#reference/0/season/season-request-example+schema)

**Comment by CozyDoomer** [comment]
I'd like to do this :)

**Comment by igorlimasan** [comment]
I'd like to do this

**Comment by beatorizu** [comment]
@CozyDoomer you can do this issue :)
